---
title: "Themed dashboard"
output: 
  flexdashboard::flex_dashboard:
    theme: yeti
    orientation: columns
    vertical_layout: fill
    horizontal_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(leaflet)
library(tidyverse)
library(bslib)
library(shiny)
library(plotly)
library(shinyWidgets)


FuncAboutButton <- function(nam) {
  actionButton(nam, "   PAGE INSTRUCTIONS", icon = icon("question-sign", lib = "glyphicon"), width = "100%")
}
```

Explore Data
====================================== 

Inputs {.sidebar data-width=330}
-------------------------------------
```{r summary_sidebar}  

observeEvent(eventExpr = input$button_aboutExploreData, {
  browseURL(here::here("About_files", "aboutExploreData.html"))})

  FuncAboutButton(nam = "button_aboutExploreData")

br()
  
  actionButton("button_refreshPlotData", "REFRESH PLOT DATA", style="color:black; border-color:black; background-color: lightgreen; width:100%; border:0px; margin:0px")# updates plots

renderUI({
  radioButtons("sel_SummarizeBy",
               label = h6(" Summarize by:"),
               choiceNames = list("ONE CHARACTERISTIC for many sites", "many characteristics for ONE SITE"),
               choiceValues = list("by_chartype", "by_station"),
               selected = "by_chartype")
  })


renderUI({
  radioButtons("sel_SummarizeBy",
               label = h6(" Summarize by:"),
               choiceNames = list("ONE CHARACTERISTIC for many sites", "many characteristics for ONE SITE"),
               choiceValues = list("by_chartype", "by_station"),
               selected = "by_chartype")
  })
```

Column
-------------------------------------
```{r}
### Map card----
# Create the map card, which will be a left-side collapsible sidebar
map_card <- bslib::card(
  full_screen = TRUE,
  card_body(
     div(style="display:flex; flex-direction:row; max-width:98%; justify-content:center; flex-wrap: wrap; align-items:center;",
    # Left side inputs
    div(style ="flex: 1 1 45%; padding:10px; justify-content:center; align-items:center;", # padding is for spacing from div edge and each other
    
    sliderInput(
    "sel_ParamMapZoom", 
    label = h6(strong("Set map zoom:")), 
    min = 1, max = 5, value = 1, step = 0.25, ticks = FALSE, dragRange = FALSE, width = "100%"),
    
    sliderInput(
    "sel_MapPointSize", 
    label = h6(strong("Resize map points:")), 
    min = -3, max = 3, value = 0, step = 1, ticks = FALSE, dragRange = FALSE, width = "100%")
  ), # end of left side inputs
  
  # Right side inputs
  div(style ="flex: 1 1 45%; padding:10px; justify-content:center; align-items:center;", # using default flex grow-shrink-size
      
      shinyWidgets::radioGroupButtons("sel_ParamMapShow",
              label = h6(strong("Show on map: ")),
              choiceNames = c("Apples", "Oranges"),
              choiceValues = c("A", "O"),
              status = "primary",
              size = "xs",
              selected = "show"),

    
    input_switch("sel_MapByYr",
                  label = h6(strong("Map summaries BY YEAR")),
                  value = FALSE
    ),
  
  sliderTextInput("sel_SurvYr", force_edges = TRUE, label = h6(strong("Choose a survey year")), choices = 2000:2020, selected = 2005, dragRange = FALSE, animate = TRUE, width = "100%")
  )
  ),
      leaflet() %>% addTiles()
)
)# end of map card


### Seasonal patterns card----
# Create the cards for plots card
seasonal_patterns_card <- bslib::card(
  full_screen = TRUE,
  card_header(
    shinyWidgets::radioGroupButtons("sel_SeasonalTimeUnit",
              label = h6("SEASONAL patterns time unit:"),
              choices = c("Day of Year" = "DayOfYr", "Week of Year" = "Wk", "Month of Year" = "Mnth", "Season of Year" = "Season"),
              selected = "Mnth",
              status = "primary",
              size = "xs"),
    br(),

selectInput("sel_HighlightSurvYr",
                  label = h6(strong("Highlight a survey year")),
                  choices = 2005:2010,
                  selected = 2005,
                  width = "200px"
                  )
  ),
card_body(
  lapply(
    lorem::ipsum(paragraphs = 5, sentences = c(10,10,10,10,10)),
    tags$p
  )
),
class = "p-0",
)

# Create the plots card, 
plots_card <- bslib::card(
  border = FALSE,
  fillable = FALSE,
  fill = FALSE,
  full_screen = FALSE,
  gap = 0,
  
  card_body( # user inputs for plots
    ## Start of plot inputs
div(style="display:flex; flex-direction:row; max-width:98%; justify-content:center; flex-wrap: wrap; align-items: center;",
    
    # Left side inputs
    div(style ="flex: 1 1 45%; padding:10px; justify-content:center; align-items:center;",
        
    shinyWidgets::radioGroupButtons("sel_PlotType",
             label = h6(strong("Plot type:")),
             choiceNames = list("Points", "Points + Smooth", "Box Plots"),
             choiceValues = list("points", "points_smooth", "box"),
             status = "primary",
             size = "xs",
             selected = "points"),
    
  shinyWidgets::dropdownButton(
    inputId = "dropdown_options",
    label = "Additional Plot Options",
    circle = FALSE,
    status = "button_menu",
    size = "xs",
    icon = icon("sliders"),
    tooltip = "Additional options for user to modify plot",

    ## Log-transform y-axes
    
    checkboxGroupInput("sel_log_y",
                     label = h6("Log-transform y-axis for:"),
                     choices = c("Yes", "No"),
                     selected = "Yes"
                     ),
                     
      ## Color by categorical character--only for point plots    
    radioButtons("sel_Categ",
                 label = h6("Color points by a categorical characteristic:"),
                 choices = c("red", "blue"),
                 selected = "blue")
  ) # End Additional Plot Options
),

# Right side inputs
    div(style ="flex: 1 1 45%; padding:10px; justify-content:center; align-items:center;",
    
      checkboxInput("sel_FreeY",
                        label = h6(strong("Allow y-axis to differ by plot")),
                        value = FALSE),

      checkboxInput("sel_CombineSites",
                        label = h6(strong("Combine sites in one plot")),
                        value = TRUE),
  
  actionButton(inputId = "button_plotTable", label = "View Table", icon = icon("table-cells", lib = "font-awesome"), style="color:black; background-color: lightblue; display:inline-block; border:1px; margin:5px")
  )
)
),
navset_card_tab(
    nav_panel(
      title = "Time Series", 
      bslib::card(
        full_screen = FALSE,
        fillable = TRUE,
        fill = TRUE,
        card_header(
          "This is a header"),
      p1 <- plot_ly(economics, x=~date, y=~uempmed),
      subplot(p1,p1,p1,p1,p1, nrows = 5, margin = 0.05)
    )
  ),
    nav_panel(title = "Seasonal Patterns", seasonal_patterns_card)
)
)



bslib::layout_sidebar(
  border = FALSE,
  fillable = FALSE,
  fill = FALSE,
    sidebar = sidebar(
      map_card,
      position = "left",
      width = "50%",
      open = TRUE),
  plots_card
)
```

Raw Data
====================================== 